server:
  port: 8082

spring:
  application:
    # 应用程序名字
    name: springcloud-porduct
  datasource: # 数据源
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: zsb
    password: 123
  messages:
    encoding: UTF-8
  resources: # 静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  thymeleaf:
    cache: false  # 使用模板缓存
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML5
eureka:
  client:
    service-url:
      # 注册中心路径:如果服务中心设置了context-path要添加context-path路径
      defaultZone: http://localhost:8081/springeureka/eureka/